# Erstelle Bayes-Zahlen für Film.csv und Nachrichten.csv
# Parametergrenzen aus den Plots abgeleitet
# erstelle ein xml-File aus Ergebnissen

# Print-Function
# borderLow: untere Grenze
# borderHigh: obere Grenze
# max: Anzahl aller Elemente
# column: zu verarbeitende Spalte
# title: Titel für Knoten
print <- function( borderLow, borderHigh,  max, column, title){
	f <- subset( column, (column >= borderLow & column < borderHigh)) 
	value <- length( f ) / max	
	cat("<",title, " low='", borderLow, "' high='", borderHigh, "' value='", value, "'/>\n", sep="")
}

cat("<brain>\n")
# Film-Werte
Film <- read.csv2("Film.csv", header=TRUE)
max <- length( Film$DOT )
cat("<film>\n")
	cat("<comma>\n")
		print( 0, 61, max, Film$COMMA, "value1")
		print( 61, 91, max, Film$COMMA, "Value2")
		print( 91, 10000, max, Film$COMMA, "Value3")
	cat("</comma>\n")
	cat("<dot>\n")
		print( 0, 51, max, Film$DOT, "Value1")
		print( 51, 71, max, Film$DOT, "Value2")
		print( 71, 91, max, Film$DOT, "Value3")
		print( 91, 10000, max, Film$DOT, "Value4")
	cat("</dot>\n")
	cat("<question>\n")
		print( 0, 1, max, Film$QUESTION, "Value1")
		print( 1, 10000, max, Film$QUESTION, "Value2")
	cat("</question>\n")
	cat("<cite>\n")
		print( 0, 1, max, Film$CITE, "Value1")
		print( 1, 10000, max, Film$CITE, "Value2")
	cat("</cite>\n")
	cat("<sentence_length_avg>\n")
		print( 0, 9, max, Film$SENTENCE_LENGTH_AVG, "Value1")
		print( 9, 10000, max, Film$SENTENCE_LENGTH_AVG, "Value2")
	cat("</sentence_length_avg>\n")
	cat("<number_with_dot>\n")
		print( 0, 2, max, Film$NUMBER_WITH_DOT, "Value1")
		print( 2, 10000, max, Film$NUMBER_WITH_DOT, "Value2")
	cat("</number_with_dot>\n")
	cat("<nl>\n")
		print( 0, 11, max, Film$NL, "Value1")
		print( 11, 16, max, Film$NL, "Value2")
		print( 16, 10000, max, Film$NL, "Value3")
	cat("</nl>\n")
	cat("<number_four>\n")
		print( 0, 11, max, Film$NUMBER_FOUR, "Value1")
		print( 11, 30, max, Film$NUMBER_FOUR, "Value2")
		print( 30, 10000, max, Film$NUMBER_FOUR, "Value3")
	cat("</number_four>\n")	
	cat("<number_rest>\n")
		print( 0, 6, max, Film$NUMBER_REST, "Value1")
		print( 6, 11, max, Film$NUMBER_REST, "Value2")
		print( 11, 10000, max, Film$NUMBER_REST, "Value3")
	cat("</number_rest>\n")	
	cat("<brack>\n")
		print( 0, 6, max, Film$BRACK, "Value1")
		print( 6, 11, max, Film$BRACK, "Value2")
		print( 11, 10000, max, Film$BRACK, "Value3")
	cat("</brack>\n")	
	cat("<sub_sentences>\n")
		print( 0, 121, max, Film$SUB_SENTENCES, "Value1")
		print( 121, 181, max, Film$SUB_SENTENCES, "Value2")
		print( 181, 10000, max, Film$SUB_SENTENCES, "Value3")
	cat("</sub_sentences>\n")			
cat("</film>\n")

# Nachrichten-Werte
News <- read.csv2("Nachrichten.csv", header=TRUE)
max <- length( News$DOT )
cat("<news>\n")
	cat("<comma>\n")
		print( 0, 55, max, News$COMMA, "Value1")
		print( 55, 145, max, News$COMMA, "Value2")
		print( 145, 10000, max, News$COMMA, "Value3")
	cat("</comma>\n")
	cat("<dot>\n")
		print( 0, 61, max, News$DOT, "Value1")
		print( 61, 101, max, News$DOT, "Value2")
		print( 101, 10000, max, News$DOT, "Value3")
	cat("</dot>\n")
	cat("<question>\n")
		print( 0, 6, max, News$QUESTION, "Value1")
		print( 6, 10000, max, News$QUESTION, "Value2")
	cat("</question>\n")
	cat("<cite>\n")
		print( 0, 6, max, News$CITE, "Value1")
		print( 6, 10000, max, News$CITE, "Value2")
	cat("</cite>\n")
	cat("<sentence_length_avg>\n")
		print( 0, 8, max, News$SENTENCE_LENGTH_AVG, "Value1")
		print( 8, 9, max, News$SENTENCE_LENGTH_AVG, "Value2")
		print( 9, 10000, max, News$SENTENCE_LENGTH_AVG, "Value3")
	cat("</sentence_length_avg>\n")
	cat("<number_with_dot>\n")
		print( 0, 2, max, News$NUMBER_WITH_DOT, "Value1")
		print( 2, 5, max, News$NUMBER_WITH_DOT, "Value2")
		print( 5, 10000, max, News$NUMBER_WITH_DOT, "Value3")		
	cat("</number_with_dot>\n")
	cat("<nl>\n")
		print( 0, 16, max, News$NL, "Value1")
		print( 16, 26, max, News$NL, "Value2")
		print( 26, 10000, max, News$NL, "Value3")
	cat("</nl>\n")
	cat("<number_four>\n")
		print( 0, 5, max, News$NUMBER_FOUR, "Value1")
		print( 5, 10000, max, News$NUMBER_FOUR, "Value2")
	cat("</number_four>\n")	
	cat("<number_rest>\n")
		print( 0, 11, max, News$NUMBER_REST, "Value1")
		print( 11, 10000, max, News$NUMBER_REST, "Value2")
	cat("</number_rest>\n")		
	cat("<brack>\n")
		print( 0, 6, max, News$BRACK, "Value1")
		print( 6, 10000, max, News$BRACK, "Value2")
	cat("</brack>\n")	
	cat("<sub_sentences>\n")
		print( 0, 151, max, News$SUB_SENTENCES, "Value1")
		print( 151, 251, max, News$SUB_SENTENCES, "Value2")
		print( 251, 10000, max, News$SUB_SENTENCES, "Value3")
	cat("</sub_sentences>\n")		
cat("</news>\n")

cat("</brain>\n")
	

