# Erstelle Bayes-Zahlen für Film.csv und Nachrichten.csv
# Parametergrenzen aus den Plots abgeleitet
# erstelle eine json aus Ergebnissen

# Print-Function
# borderLow: untere Grenze
# borderHigh: obere Grenze
# max: Anzahl aller Elemente
# column: zu verarbeitende Spalte
# title: Title für JSON-Zwecke benötigt
# comma: für JSON, default=","
print <- function( borderLow, borderHigh,  max, column, title, comma=","){
	f <- subset( column, (column >= borderLow & column < borderHigh)) 
	value <- length( f ) / max	
	cat("\t\t\t",title,":{\n")	
	cat("\t\t\t\t\"BorderLow\": ", borderLow, ",\n")
	cat("\t\t\t\t\"BorderHigh\": ", borderHigh, ",\n")
	cat("\t\t\t\t\"Value\": ", value, "\n")
	cat("\t\t\t}", comma, "\n")
}

cat("{\n")
# Film-Werte
Film <- read.csv2("Film.csv", header=TRUE)
max <- length( Film$DOT )
cat("\t\"Film\": {\n")
	cat("\t\t\"Kom\":{\n")
		print( 0, 61, max, Film$KOM, "\"Value1\"")
		print( 61, 100, max, Film$KOM, "\"Value2\"")
		print( 100, 10000, max, Film$KOM, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"DOT\":{\n")
		print( 0, 61, max, Film$DOT, "\"Value1\"")
		print( 61, 71, max, Film$DOT, "\"Value2\"")
		print( 71, 10000, max, Film$DOT, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"AUS\":{\n")
		print( 0, 2, max, Film$AUS, "\"Value1\"")
		print( 2, 10000, max, Film$AUS, "\"Value2\"")
	cat("\t\t},\n")
	cat("\t\t\"QUES\":{\n")
		print( 0, 3, max, Film$QUES, "\"Value1\"")
		print( 3, 10000, max, Film$QUES, "\"Value2\"")
	cat("\t\t},\n")
	cat("\t\t\"CITE\":{\n")
		print( 0, 5, max, Film$CITE, "\"Value1\"")
		print( 5, 15, max, Film$CITE, "\"Value2\"")
		print( 15, 10000, max, Film$CITE, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"Satzlaenge\":{\n")
		print( 0, 17, max, Film$Satzlaenge, "\"Value1\"")
		print( 17, 20, max, Film$Satzlaenge, "\"Value2\"")
		print( 20, 10000, max, Film$Satzlaenge, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"Vergangenheit\":{\n")
		print( 0, 20, max, Film$Vergangenheit, "\"Value1\"")
		print( 20, 25, max, Film$Vergangenheit, "\"Value2\"")
		print( 25, 10000, max, Film$Vergangenheit, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"NUMBERwithDOT\":{\n")
		print( 0, 2, max, Film$NUMBERwithDOT, "\"Value1\"")
		print( 2, 10000, max, Film$NUMBERwithDOT, "\"Value2\"")
	cat("\t\t},\n")
	cat("\t\t\"NL\":{\n")
		print( 0, 10, max, Film$NL, "\"Value1\"")
		print( 10, 15, max, Film$NL, "\"Value2\"")
		print( 15, 10000, max, Film$NL, "\"Value3\"", ",")
	cat("\t\t},\n")
	cat("\t\t\"NUMBERfour\":{\n")
		print( 0, 10, max, Film$NUMBERfour, "\"Value1\"")
		print( 10, 40, max, Film$NUMBERfour, "\"Value2\"")
		print( 40, 10000, max, Film$NUMBERfour, "\"Value3\"")
	cat("\t\t},\n")	
	cat("\t\t\"NUMBERrest\":{\n")
		print( 0, 6, max, Film$NUMBERrest, "\"Value1\"")
		print( 6, 10, max, Film$NUMBERrest, "\"Value2\"")
		print( 10, 10000, max, Film$NUMBERrest, "\"Value3\"", " ")
	cat("\t\t}\n")		
cat("\t}\n")

# Nachrichten-Werte
News <- read.csv2("Nachrichten.csv", header=TRUE)
max <- length( News$DOT )
cat("\t\"News\": {\n")
	cat("\t\t\"Kom\":{\n")
		print( 0, 60, max, News$KOM, "\"Value1\"")
		print( 60, 141, max, News$KOM, "\"Value2\"")
		print( 141, 10000, max, News$KOM, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"DOT\":{\n")
		print( 0, 81, max, News$DOT, "\"Value1\"")
		print( 81, 121, max, News$DOT, "\"Value2\"")
		print( 121, 10000, max, News$DOT, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"AUS\":{\n")
		print( 0, 1, max, News$AUS, "\"Value1\"")
		print( 1, 5, max, News$AUS, "\"Value2\"")
		print( 5, 10000, max, News$AUS, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"QUES\":{\n")
		print( 0, 3, max, News$QUES, "\"Value1\"")
		print( 3, 10, max, News$QUES, "\"Value2\"")
		print( 10, 10000, max, News$QUES, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"CITE\":{\n")
		print( 0, 20, max, News$CITE, "\"Value1\"")
		print( 20, 10000, max, News$CITE, "\"Value2\"")
	cat("\t\t},\n")
	cat("\t\t\"Satzlaenge\":{\n")
		print( 0, 18, max, News$Satzlaenge, "\"Value1\"")
		print( 18, 23, max, News$Satzlaenge, "\"Value2\"")
		print( 23, 10000, max, News$Satzlaenge, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"Vergangenheit\":{\n")
		print( 0, 10, max, News$Vergangenheit, "\"Value1\"")
		print( 10, 30, max, News$Vergangenheit, "\"Value2\"")
		print( 30, 10000, max, News$Vergangenheit, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"NUMBERwithDOT\":{\n")
		print( 0, 2, max, News$NUMBERwithDOT, "\"Value1\"")
		print( 2, 5, max, News$NUMBERwithDOT, "\"Value2\"")
		print( 5, 10000, max, News$NUMBERwithDOT, "\"Value3\"")		
	cat("\t\t},\n")
	cat("\t\t\"NL\":{\n")
		print( 0, 15, max, News$NL, "\"Value1\"")
		print( 15, 25, max, News$NL, "\"Value2\"")
		print( 25, 10000, max, News$NL, "\"Value3\"")
	cat("\t\t},\n")
	cat("\t\t\"NUMBERfour\":{\n")
		print( 0, 5, max, News$NUMBERfour, "\"Value1\"")
		print( 5, 10000, max, News$NUMBERfour, "\"Value2\"")
	cat("\t\t},\n")	
	cat("\t\t\"NUMBERrest\":{\n")
		print( 0, 11, max, News$NUMBERrest, "\"Value1\"")
		print( 11, 10000, max, News$NUMBERrest, "\"Value2\"", " ")
	cat("\t\t}\n")		
cat("\t}\n")

cat("}")
	

