# Erstelle Bayes-Zahlen für Film.csv und Nachrichten.csv
# Parametergrenzen aus den Plots abgeleitet
# erstelle ein xml-File aus Ergebnissen

# Print-Function
# borderLow: untere Grenze
# borderHigh: obere Grenze
# max: Anzahl aller Elemente
# column: zu verarbeitende Spalte
# title: Titel für Knoten
print <- function( borderLow, borderHigh,  max, column, title){
	f <- subset( column, (column >= borderLow & column < borderHigh)) 
	value <- length( f ) / max	
	cat("<",title, " low='", borderLow, "' high='", borderHigh, "' value='", value, "'/>\n", sep="")
}

cat("<brain>\n")
# Film-Werte
Film <- read.csv2("Film.csv", header=TRUE)
max <- length( Film$DOT )
cat("<film>\n")
	cat("<comma>\n")
		print( 0, 61, max, Film$COMMA, "value1")
		print( 61, 100, max, Film$COMMA, "Value2")
		print( 100, 10000, max, Film$COMMA, "Value3")
	cat("</comma>\n")
	cat("<dot>\n")
		print( 0, 61, max, Film$DOT, "Value1")
		print( 61, 71, max, Film$DOT, "Value2")
		print( 71, 10000, max, Film$DOT, "Value3")
	cat("</dot>\n")
	cat("<exclamation>\n")
		print( 0, 2, max, Film$EXCLAMATION, "Value1")
		print( 2, 10000, max, Film$EXCLAMATION, "Value2")
	cat("</exclamation>\n")
	cat("<question>\n")
		print( 0, 3, max, Film$QUESTION, "Value1")
		print( 3, 10000, max, Film$QUESTION, "Value2")
	cat("</question>\n")
	cat("<cite>\n")
		print( 0, 1, max, Film$CITE, "Value1")
		print( 1, 10000, max, Film$CITE, "Value2")
	cat("</cite>\n")
	cat("<sentence_length>\n")
		print( 0, 17, max, Film$SENTENCE_LENGTH, "Value1")
		print( 17, 20, max, Film$SENTENCE_LENGTH, "Value2")
		print( 20, 10000, max, Film$SENTENCE_LENGTH, "Value3")
	cat("</sentence_length>\n")
	cat("<past>\n")
		print( 0, 20, max, Film$PAST, "Value1")
		print( 20, 25, max, Film$PAST, "Value2")
		print( 25, 10000, max, Film$PAST, "Value3")
	cat("</past>\n")
	cat("<number_with_dot>\n")
		print( 0, 2, max, Film$NUMBER_WITH_DOT, "Value1")
		print( 2, 10000, max, Film$NUMBER_WITH_DOT, "Value2")
	cat("</number_with_dot>\n")
	cat("<nl>\n")
		print( 0, 10, max, Film$NL, "Value1")
		print( 10, 15, max, Film$NL, "Value2")
		print( 15, 10000, max, Film$NL, "Value3")
	cat("</nl>\n")
	cat("<number_four>\n")
		print( 0, 10, max, Film$NUMBER_FOUR, "Value1")
		print( 10, 40, max, Film$NUMBER_FOUR, "Value2")
		print( 40, 10000, max, Film$NUMBER_FOUR, "Value3")
	cat("</number_four>\n")	
	cat("<number_rest>\n")
		print( 0, 6, max, Film$NUMBER_REST, "Value1")
		print( 6, 10, max, Film$NUMBER_REST, "Value2")
		print( 10, 10000, max, Film$NUMBER_REST, "Value3")
	cat("</number_rest>\n")	
	cat("<brack>\n")
		print( 0, 6, max, Film$BRACK, "Value1")
		print( 6, 10, max, Film$BRACK, "Value2")
		print( 10, 10000, max, Film$BRACK, "Value3")
	cat("</brack>\n")	
		
cat("</film>\n")

# Nachrichten-Werte
News <- read.csv2("Nachrichten.csv", header=TRUE)
max <- length( News$DOT )
cat("<news>\n")
	cat("<comma>\n")
		print( 0, 60, max, News$COMMA, "Value1")
		print( 60, 141, max, News$COMMA, "Value2")
		print( 141, 10000, max, News$COMMA, "Value3")
	cat("</comma>\n")
	cat("<dot>\n")
		print( 0, 81, max, News$DOT, "Value1")
		print( 81, 121, max, News$DOT, "Value2")
		print( 121, 10000, max, News$DOT, "Value3")
	cat("</dot>\n")
	cat("<exclamation>\n")
		print( 0, 1, max, News$EXCLAMATION, "Value1")
		print( 1, 5, max, News$EXCLAMATION, "Value2")
		print( 5, 10000, max, News$EXCLAMATION, "Value3")
	cat("</exclamation>\n")
	cat("<question>\n")
		print( 0, 3, max, News$QUESTION, "Value1")
		print( 3, 10, max, News$QUESTION, "Value2")
		print( 10, 10000, max, News$QUESTION, "Value3")
	cat("</question>\n")
	cat("<cite>\n")
		print( 0, 5, max, News$CITE, "Value1")
		print( 5, 10000, max, News$CITE, "Value2")
	cat("</cite>\n")
	cat("<sentence_length>\n")
		print( 0, 18, max, News$SENTENCE_LENGTH, "Value1")
		print( 18, 23, max, News$SENTENCE_LENGTH, "Value2")
		print( 23, 10000, max, News$SENTENCE_LENGTH, "Value3")
	cat("</sentence_length>\n")
	cat("<past>\n")
		print( 0, 10, max, News$PAST, "Value1")
		print( 10, 30, max, News$PAST, "Value2")
		print( 30, 10000, max, News$PAST, "Value3")
	cat("</past>\n")
	cat("<number_with_dot>\n")
		print( 0, 2, max, News$NUMBER_WITH_DOT, "Value1")
		print( 2, 5, max, News$NUMBER_WITH_DOT, "Value2")
		print( 5, 10000, max, News$NUMBER_WITH_DOT, "Value3")		
	cat("</number_with_dot>\n")
	cat("<nl>\n")
		print( 0, 15, max, News$NL, "Value1")
		print( 15, 25, max, News$NL, "Value2")
		print( 25, 10000, max, News$NL, "Value3")
	cat("</nl>\n")
	cat("<number_four>\n")
		print( 0, 5, max, News$NUMBER_FOUR, "Value1")
		print( 5, 10000, max, News$NUMBER_FOUR, "Value2")
	cat("</number_four>\n")	
	cat("<number_rest>\n")
		print( 0, 11, max, News$NUMBER_REST, "Value1")
		print( 11, 10000, max, News$NUMBER_REST, "Value2")
	cat("</number_rest>\n")		
	cat("<brack>\n")
		print( 0, 6, max, Film$BRACK, "Value1")
		print( 6, 10, max, Film$BRACK, "Value2")
	cat("</brack>\n")	
cat("</news>\n")

cat("</brain>\n")
	

