# Erstelle Bayes-Zahlen für Film.csv und Nachrichten.csv
# Parametergrenzen aus den Plots abgeleitet
# erstelle ein xml-File aus Ergebnissen

# Print-Function
# borderLow: untere Grenze
# borderHigh: obere Grenze
# max: Anzahl aller Elemente
# column: zu verarbeitende Spalte
# title: Titel für Knoten
print <- function( borderLow, borderHigh,  max, column, title){
	f <- subset( column, (column >= borderLow & column < borderHigh)) 
	value <- length( f ) / max	
	cat("<",title, " low='", borderLow, "' high='", borderHigh, "' value='", value, "'/>\n", sep="")
}

cat("<brain>\n")
# Film-Werte
Film <- read.csv2("Film.csv", header=TRUE)
max <- length( Film$DOT )
cat("<film>\n")
	cat("<comma>\n")
		print( 0, 60, max, Film$COMMA, "value1")
		print( 60, 90, max, Film$COMMA, "Value2")
		print( 90, 10000, max, Film$COMMA, "Value3")
	cat("</comma>\n")
	cat("<dot>\n")
		print( 0, 50, max, Film$DOT, "Value1")
		print( 50, 70, max, Film$DOT, "Value2")
		print( 70, 90, max, Film$DOT, "Value3")
		print( 90, 10000, max, Film$DOT, "Value4")
	cat("</dot>\n")
	cat("<question>\n")
		print( 0, 1, max, Film$QUESTION, "Value1")
		print( 1, 5, max, Film$QUESTION, "Value2")
		print( 5, 10000, max, Film$QUESTION, "Value3")
	cat("</question>\n")
	cat("<cite>\n")
		print( 0, 1, max, Film$CITE, "Value1")
		print( 1, 10000, max, Film$CITE, "Value2")
	cat("</cite>\n")
	cat("<sentence_length_avg>\n")
		print( 0, 13, max, Film$SENTENCE_LENGTH_AVG, "Value1")
		print( 13, 14, max, Film$SENTENCE_LENGTH_AVG, "Value2")
		print( 14, 10000, max, Film$SENTENCE_LENGTH_AVG, "Value3")
	cat("</sentence_length_avg>\n")
	cat("<number_with_dot>\n")
		print( 0, 1, max, Film$NUMBER_WITH_DOT, "Value1")
		print( 1, 10000, max, Film$NUMBER_WITH_DOT, "Value2")
	cat("</number_with_dot>\n")
	cat("<nl>\n")
		print( 0, 10, max, Film$NL, "Value1")
		print( 10, 15, max, Film$NL, "Value2")
		print( 15, 10000, max, Film$NL, "Value3")
	cat("</nl>\n")
	cat("<number_four>\n")
		print( 0, 10, max, Film$NUMBER_FOUR, "Value1")
		print( 10, 30, max, Film$NUMBER_FOUR, "Value2")
		print( 30, 10000, max, Film$NUMBER_FOUR, "Value3")
	cat("</number_four>\n")	
	cat("<number_rest>\n")
		print( 0, 5, max, Film$NUMBER_REST, "Value1")
		print( 5, 10, max, Film$NUMBER_REST, "Value2")
		print( 10, 10000, max, Film$NUMBER_REST, "Value3")
	cat("</number_rest>\n")	
	cat("<brack>\n")
		print( 0, 5, max, Film$BRACK, "Value1")
		print( 5, 10, max, Film$BRACK, "Value2")
		print( 10, 10000, max, Film$BRACK, "Value3")
	cat("</brack>\n")	
	cat("<sub_sentences>\n")
		print( 0, 140, max, Film$SUB_SENTENCES, "Value1")
		print( 140, 180, max, Film$SUB_SENTENCES, "Value2")
		print( 180, 10000, max, Film$SUB_SENTENCES, "Value3")
	cat("</sub_sentences>\n")	
	cat("<past>\n")
		print( 0, 300, max, Film$PAST, "Value1")
		print( 300, 10000, max, Film$PAST, "Value2")
	cat("</past>\n")		
	cat("<noun>\n")
		print( 0, 350, max, Film$NOUN, "Value1")
		print( 350, 500, max, Film$NOUN, "Value2")
		print( 500, 10000, max, Film$NOUN, "Value3")
	cat("</noun>\n")	
	cat("<sentence_length_max>\n")
		print( 0, 45, max, Film$SENTENCE_LENGTH_MAX, "Value1")
		print( 45, 60, max, Film$SENTENCE_LENGTH_MAX, "Value2")
		print( 60, 10000, max, Film$SENTENCE_LENGTH_MAX, "Value3")
	cat("</sentence_length_max>\n")	
	cat("<word_length_3>\n")
		print( 0, 300, max, Film$WORD_LENGTH_3, "Value1")
		print( 300, 350, max, Film$WORD_LENGTH_3, "Value2")
		print( 350, 10000, max, Film$WORD_LENGTH_3, "Value3")
	cat("</word_length_3>\n")
	cat("<word_length_4>\n")
		print( 0, 100, max, Film$WORD_LENGTH_4, "Value1")
		print( 100, 120, max, Film$WORD_LENGTH_4, "Value2")
		print( 120, 10000, max, Film$WORD_LENGTH_4, "Value3")
	cat("</word_length_4>\n")	
	cat("<word_length_5>\n")
		print( 0, 80, max, Film$WORD_LENGTH_5, "Value1")
		print( 80, 100, max, Film$WORD_LENGTH_5, "Value2")
		print( 100, 120, max, Film$WORD_LENGTH_5, "Value3")
		print( 120, 10000, max, Film$WORD_LENGTH_5, "Value4")		
	cat("</word_length_5>\n")	
	cat("<word_length_6>\n")
		print( 0, 70, max, Film$WORD_LENGTH_6, "Value1")
		print( 70, 80, max, Film$WORD_LENGTH_6, "Value2")
		print( 80, 10000, max, Film$WORD_LENGTH_6, "Value3")
	cat("</word_length_6>\n")	
	cat("<word_length_7>\n")
		print( 0, 40, max, Film$WORD_LENGTH_7, "Value1")
		print( 40, 45, max, Film$WORD_LENGTH_7, "Value2")
		print( 45, 10000, max, Film$WORD_LENGTH_7, "Value3")
	cat("</word_length_7>\n")	
	cat("<word_length_8>\n")
		print( 0, 200, max, Film$WORD_LENGTH_8, "Value1")
		print( 200, 245, max, Film$WORD_LENGTH_8, "Value2")
		print( 245, 300, max, Film$WORD_LENGTH_8, "Value3")
		print( 300, 10000, max, Film$WORD_LENGTH_8, "Value4")		
	cat("</word_length_8>\n")	
	cat("<noun_length_3>\n")
		print( 0, 20, max, Film$NOUN_LENGTH_3, "Value1")
		print( 20, 40, max, Film$NOUN_LENGTH_3, "Value2")
		print( 40, 10000, max, Film$NOUN_LENGTH_3, "Value3")
	cat("</noun_length_3>\n")
	cat("<noun_length_4>\n")
		print( 0, 60, max, Film$NOUN_LENGTH_4, "Value1")
		print( 60, 70, max, Film$NOUN_LENGTH_4, "Value2")
		print( 70, 10000, max, Film$NOUN_LENGTH_4, "Value3")
	cat("</noun_length_4>\n")	
	cat("<noun_length_5>\n")
		print( 0, 60, max, Film$NOUN_LENGTH_5, "Value1")
		print( 60, 70, max, Film$NOUN_LENGTH_5, "Value2")
		print( 70, 10000, max, Film$NOUN_LENGTH_5, "Value3")		
	cat("</noun_length_5>\n")	
	cat("<noun_length_6>\n")
		print( 0, 40, max, Film$NOUN_LENGTH_6, "Value1")
		print( 40, 80, max, Film$NOUN_LENGTH_6, "Value2")
		print( 80, 10000, max, Film$NOUN_LENGTH_6, "Value3")
	cat("</noun_length_6>\n")	
	cat("<noun_length_7>\n")
		print( 0, 50, max, Film$NOUN_LENGTH_7, "Value1")
		print( 50, 10000, max, Film$NOUN_LENGTH_7, "Value2")
	cat("</noun_length_7>\n")	
	cat("<noun_length_8>\n")
		print( 0, 100, max, Film$NOUN_LENGTH_8, "Value1")
		print( 100, 200, max, Film$NOUN_LENGTH_8, "Value2")
		print( 200, 10000, max, Film$NOUN_LENGTH_8, "Value3")		
	cat("</noun_length_8>\n")	
cat("</film>\n")

# Nachrichten-Werte
News <- read.csv2("Nachrichten.csv", header=TRUE)
max <- length( News$DOT )
cat("<news>\n")
	cat("<comma>\n")
		print( 0, 50, max, News$COMMA, "Value1")
		print( 50, 145, max, News$COMMA, "Value2")
		print( 145, 10000, max, News$COMMA, "Value3")
	cat("</comma>\n")
	cat("<dot>\n")
		print( 0, 60, max, News$DOT, "Value1")
		print( 60, 100, max, News$DOT, "Value2")
		print( 100, 10000, max, News$DOT, "Value3")
	cat("</dot>\n")
	cat("<question>\n")
		print( 0, 5, max, News$QUESTION, "Value1")
		print( 5, 10000, max, News$QUESTION, "Value2")
	cat("</question>\n")
	cat("<cite>\n")
		print( 0, 5, max, News$CITE, "Value1")
		print( 5, 15, max, News$CITE, "Value2")
		print( 15, 10000, max, News$CITE, "Value3")
	cat("</cite>\n")
	cat("<sentence_length_avg>\n")
		print( 0, 11, max, News$SENTENCE_LENGTH_AVG, "Value1")
		print( 11, 13, max, News$SENTENCE_LENGTH_AVG, "Value2")
		print( 13, 10000, max, News$SENTENCE_LENGTH_AVG, "Value3")
	cat("</sentence_length_avg>\n")
	cat("<number_with_dot>\n")
		print( 0, 1, max, News$NUMBER_WITH_DOT, "Value1")
		print( 1, 5, max, News$NUMBER_WITH_DOT, "Value2")
		print( 5, 10000, max, News$NUMBER_WITH_DOT, "Value3")		
	cat("</number_with_dot>\n")
	cat("<nl>\n")
		print( 0, 15, max, News$NL, "Value1")
		print( 15, 25, max, News$NL, "Value2")
		print( 25, 10000, max, News$NL, "Value3")
	cat("</nl>\n")
	cat("<number_four>\n")
		print( 0, 4, max, News$NUMBER_FOUR, "Value1")
		print( 4, 8, max, News$NUMBER_FOUR, "Value2")
		print( 8, 10000, max, News$NUMBER_FOUR, "Value3")
	cat("</number_four>\n")	
	cat("<number_rest>\n")
		print( 0, 5, max, News$NUMBER_REST, "Value1")
		print( 5, 15, max, News$NUMBER_REST, "Value2")
		print( 15, 10000, max, News$NUMBER_REST, "Value3")
	cat("</number_rest>\n")		
	cat("<brack>\n")
		print( 0, 5, max, News$BRACK, "Value1")
		print( 5, 10000, max, News$BRACK, "Value2")
	cat("</brack>\n")	
	cat("<sub_sentences>\n")
		print( 0, 100, max, News$SUB_SENTENCES, "Value1")
		print( 100, 150, max, News$SUB_SENTENCES, "Value2")
		print( 150, 250, max, News$SUB_SENTENCES, "Value3")
		print( 250, 10000, max, News$SUB_SENTENCES, "Value4")
	cat("</sub_sentences>\n")
	cat("<past>\n")
		print( 0, 300, max, News$PAST, "Value1")
		print( 300, 10000, max, News$PAST, "Value2")
	cat("</past>\n")			
	cat("<noun>\n")
		print( 0, 400, max, News$NOUN, "Value1")
		print( 400, 500, max, News$NOUN, "Value2")
		print( 500, 600, max, News$NOUN, "Value3")
		print( 600, 10000, max, News$NOUN, "Value4")
	cat("</noun>\n")
	cat("<sentence_length_max>\n")
		print( 0, 40, max, News$SENTENCE_LENGTH_MAX, "Value1")
		print( 40, 50, max, News$SENTENCE_LENGTH_MAXNOUN, "Value2")
		print( 50, 60, max, News$SENTENCE_LENGTH_MAX, "Value3")
		print( 60, 10000, max, News$SENTENCE_LENGTH_MAX, "Value4")
	cat("</sentence_length_max>\n")	
	cat("<word_length_3>\n")
		print( 0, 300, max, News$WORD_LENGTH_3, "Value1")
		print( 300, 400, max, News$WORD_LENGTH_3, "Value2")
		print( 400, 10000, max, News$WORD_LENGTH_3, "Value3")
	cat("</word_length_3>\n")
	cat("<word_length_4>\n")
		print( 0, 120, max, News$WORD_LENGTH_4, "Value1")
		print( 120, 160, max, News$WORD_LENGTH_4, "Value2")
		print( 160, 10000, max, News$WORD_LENGTH_4, "Value3")
	cat("</word_length_4>\n")	
	cat("<word_length_5>\n")
		print( 0, 100, max, News$WORD_LENGTH_5, "Value1")
		print( 100, 120, max, News$WORD_LENGTH_5, "Value2")
		print( 120, 140, max, News$WORD_LENGTH_5, "Value3")
		print( 140, 10000, max, News$WORD_LENGTH_5, "Value4")		
	cat("</word_length_5>\n")	
	cat("<word_length_6>\n")
		print( 0, 60, max, News$WORD_LENGTH_6, "Value1")
		print( 60, 80, max, News$WORD_LENGTH_6, "Value2")
		print( 80, 90, max, News$WORD_LENGTH_6, "Value3")
		print( 90, 10000, max, News$WORD_LENGTH_6, "Value4")
	cat("</word_length_6>\n")	
	cat("<word_length_7>\n")
		print( 0, 35, max, News$WORD_LENGTH_7, "Value1")
		print( 35, 50, max, News$WORD_LENGTH_7, "Value2")
		print( 50, 10000, max, News$WORD_LENGTH_7, "Value3")
	cat("</word_length_7>\n")	
	cat("<word_length_8>\n")
		print( 0, 250, max, News$WORD_LENGTH_8, "Value1")
		print( 250, 300, max, News$WORD_LENGTH_8, "Value2")
		print( 300, 10000, max, News$WORD_LENGTH_8, "Value4")		
	cat("</word_length_8>\n")	
	cat("<noun_length_3>\n")
		print( 0, 40, max, News$NOUN_LENGTH_3, "Value1")
		print( 40, 60, max, News$NOUN_LENGTH_3, "Value2")
		print( 60, 10000, max, News$NOUN_LENGTH_3, "Value3")
	cat("</noun_length_3>\n")
	cat("<noun_length_4>\n")
		print( 0, 30, max, News$NOUN_LENGTH_4, "Value1")
		print( 30, 50, max, News$NOUN_LENGTH_4, "Value2")
		print( 50, 60, max, News$NOUN_LENGTH_4, "Value3")
		print( 60, 10000, max, News$NOUN_LENGTH_4, "Value4")
	cat("</noun_length_4>\n")	
	cat("<noun_length_5>\n")
		print( 0, 40, max, News$NOUN_LENGTH_5, "Value1")
		print( 40, 60, max, News$NOUN_LENGTH_5, "Value2")
		print( 60, 10000, max, News$NOUN_LENGTH_5, "Value3")		
	cat("</noun_length_5>\n")	
	cat("<noun_length_6>\n")
		print( 0, 50, max, News$NOUN_LENGTH_6, "Value1")
		print( 50, 70, max, News$NOUN_LENGTH_6, "Value2")
		print( 70, 10000, max, News$NOUN_LENGTH_6, "Value3")
	cat("</noun_length_6>\n")	
	cat("<noun_length_7>\n")
		print( 0, 30, max, News$NOUN_LENGTH_7, "Value1")
		print( 30, 50, max, News$NOUN_LENGTH_7, "Value2")
		print( 50, 10000, max, News$NOUN_LENGTH_7, "Value3")
	cat("</noun_length_7>\n")	
	cat("<noun_length_8>\n")
		print( 0, 150, max, News$NOUN_LENGTH_8, "Value1")
		print( 150, 250, max, News$NOUN_LENGTH_8, "Value2")
		print( 250, 10000, max, News$NOUN_LENGTH_8, "Value3")		
	cat("</noun_length_8>\n")
cat("</news>\n")

cat("</brain>\n")
	

